// Data extracted from the CSV snippet and merged with the original approversData
const companyUserIdsMap = {
  // Data extracted from "EM Approver list.xlsx - Sheet3.csv" snippets, excluding 'NGRPTIME'
  "ADCRO": ["NGMCLON", "NGMCCON", "NGMCCOA"],
  "JOCAP": ["NGMCLLO", "NGMCLON", "NGMCSCO", "NGMCINT", "NGDOOR"],
  "KLEWIS": ["NGMCLON", "NGMCUK"],
  "TUDAL": ["NGMCLON", "NGMCINT", "NGMCCOA", "NGMCLSE"],
  "BEWIL": ["NGMCLON", "NGMCKRM", "NGMCOUT", "NGMCREP"],
  "EBRAD": ["NGMCLON"],
  "CTURN": ["NGMCNOR", "NGMCBRL", "NGMCBRB", "NGMCNAL", "NGMCCOA", "NGMCALL", "NGMCUK", "NGMCLON", "NGOPEM"],
  "IMACD": ["NGMCMBA", "NGMCLON", "NGMCNUC", "NGMCALL", "NGMCBRL", "NGMCUK", "NGMCINT", "NGMCCOA"],
  "JBOCK": ["NGMCMBA", "NGMCLON", "NGMCNUC", "NGMCALL", "NGOPEN"],
  "KAREI": ["NGMCLON", "NGMCKRM"],
  "KGRAC": ["NGMCINT", "NGMCALL", "NGMCLON"],
  "MAHOW": ["NGMCMBA", "NGMCLON", "NGMCINT"],
  "SCUSH": ["NGMCINT", "NGMCLON"]
};

export const approversData = [{
  id: "ADCRO",
  firstName: "ADAM",
  lastName: "CROW",
  email: "adam.crow@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPROV",
  businessUnit: "All"
}, {
  id: "ADENE",
  firstName: "ADEEL",
  lastName: "NEHIM",
  email: "adeel.nehim@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRBUY",
  businessUnit: "International",
  specialty: "Social"
}, {
  id: "ADMCC",
  firstName: "ADEOLA",
  lastName: "MCCABE",
  email: "adeola.mccabe@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRBUY",
  businessUnit: "International",
  specialty: "Social"
}, {
  id: "ADSMI",
  firstName: "ADAM",
  lastName: "SMITH",
  email: "adam.smith1@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRBUY",
  businessUnit: "PPC",
  specialty: "PPC"
}, {
  id: "AMGIBS",
  firstName: "AMELIA",
  lastName: "MONKS",
  email: "amelia.monks@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRBUY",
  businessUnit: "BU5"
}, {
  id: "AMILE",
  firstName: "ANA",
  lastName: "CUELLAR",
  email: "ana.cuellar@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRBUY",
  businessUnit: "SEO",
  specialty: "SEO"
}, {
  id: "AMUEL",
  firstName: "ADRIAN",
  lastName: "MUELLER",
  email: "adrian.mueller@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPROV",
  businessUnit: "Global"
}, {
  id: "ANCOO",
  firstName: "ANDREW",
  lastName: "COOK",
  email: "andrew.cook@essencemediacom.com",
  officeName: "MEDIACOM NORTH",
  securityGroup: "PRAPRGBY",
  businessUnit: "North"
}, {
  id: "ANGIM",
  firstName: "ANNA",
  lastName: "GIM",
  email: "anna.gim@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRBUY",
  businessUnit: "International"
}, {
  id: "ANIKO",
  firstName: "ATHINA",
  lastName: "NIKOL",
  email: "athina.nikol@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRBUY",
  businessUnit: "International"
}, {
  id: "APYKE",
  firstName: "ADAM",
  lastName: "PYKE",
  email: "adam.pyke@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRBUY",
  businessUnit: "BU12",
  specialty: "PPC"
}, {
  id: "AROBE",
  firstName: "AMY",
  lastName: "ROBERTS",
  email: "amy.roberts@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRBUY",
  businessUnit: "BG3"
}, {
  id: "ASHEI",
  firstName: "ASHLEIGH",
  lastName: "HEITMAN",
  email: "ashleigh.heitman@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPROV",
  businessUnit: "International"
}, {
  id: "ASTEP",
  firstName: "ADAM",
  lastName: "STEPHENS",
  email: "adam.stephens@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPROV",
  businessUnit: "International"
}, {
  id: "AWIJE",
  firstName: "ADRIAN",
  lastName: "WIJENATHAN",
  email: "adrian.wijenathan@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRBUY",
  businessUnit: "Global"
}, {
  id: "BDRUR",
  firstName: "BETH",
  lastName: "DRURY",
  email: "beth.drury@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRBUY",
  businessUnit: "International"
}, {
  id: "BESTA",
  firstName: "BEN",
  lastName: "STANHOPE",
  email: "ben.stanhope1@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRPO",
  businessUnit: "Global"
}, {
  id: "BEWIL",
  firstName: "BECCI",
  lastName: "WILSON",
  email: "becci.wilson@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRBUY",
  businessUnit: "B12"
}, {
  id: "BISAM",
  firstName: "BILLY",
  lastName: "SAMUELS",
  email: "billy.samuels@essencemediacom.com",
  officeName: "MEDIACOM NORTH",
  securityGroup: "PRAPRGBY",
  businessUnit: "North"
}, {
  id: "BMALA",
  firstName: "BEN",
  lastName: "MALAM",
  email: "ben.malam@essencemediacom.com",
  officeName: "MEDIACOM NORTH",
  securityGroup: "PRAPRGBY",
  businessUnit: "North"
}, {
  id: "BSHEA",
  firstName: "BRIONY",
  lastName: "SHEARD",
  email: "briony.sheard@essencemediacom.com",
  officeName: "MEDIACOM NORTH",
  securityGroup: "PRAPROV",
  businessUnit: "North"
}, {
  id: "CBECK",
  firstName: "CHRISTOFER",
  lastName: "BECKMAN",
  email: "christofer.beckman@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRBUY",
  businessUnit: "International"
}, {
  id: "CMAST",
  firstName: "CAROLINE",
  lastName: "MASTROMAURO",
  email: "caroline.mastromauro@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRBUY",
  businessUnit: "PST"
}, {
  id: "CMCWH",
  firstName: "CAROLINE",
  lastName: "MCWHIRTER",
  email: "caroline.mcwhirter@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPROV",
  businessUnit: "Global"
}, {
  id: "CRIDS",
  firstName: "CARYS",
  lastName: "PROFITDALE",
  email: "carys.profitdale@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRBUY",
  businessUnit: "BU12"
}, {
  id: "CROSE",
  firstName: "CHEYENNE",
  lastName: "ROSE",
  email: "cheyenne.rose@essencemediacom.com",
  officeName: "ESSENCE",
  securityGroup: "PRAPRBUY",
  businessUnit: "International"
}, {
  id: "CSAUN",
  firstName: "CHARLIE",
  lastName: "SAUNDERS",
  email: "charlie.saunders@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRBUY",
  businessUnit: "International"
}, {
  id: "CTURN",
  firstName: "CHRIS",
  lastName: "TURNER",
  email: "chris.turner@essencemediacom.com",
  officeName: "MEDIACOM NORTH",
  securityGroup: "PRAPROV",
  businessUnit: "PST",
  specialty: "PST"
}, {
  id: "CTUTT",
  firstName: "CONNOR",
  lastName: "TUTTLE",
  email: "connor.tuttle@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRBUY",
  businessUnit: "International"
}, {
  id: "DADAR",
  firstName: "DANIELLE",
  lastName: "DARKO",
  email: "danielle.darko@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPBMQS",
  businessUnit: "International"
}, {
  id: "DANBE",
  firstName: "DANIELLE",
  lastName: "BENNETT",
  email: "danielle.bennett@essencemediacom.com",
  officeName: "MEDIACOM NORTH",
  securityGroup: "PRAPRGBY",
  businessUnit: "North"
}, {
  id: "DAROBI",
  firstName: "DAN",
  lastName: "ROBINSON",
  email: "dan.robinson@essencemediacom.com",
  officeName: "MEDIACOM NORTH",
  securityGroup: "PRAPRGBY",
  businessUnit: "North"
}, {
  id: "DCABU",
  firstName: "DAMLA",
  lastName: "CABUK",
  email: "damla.cabuk@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRBUY",
  businessUnit: "International"
}, {
  id: "DDWIN",
  firstName: "DANIQUE",
  lastName: "DE WINTER",
  email: "danique.dewinter@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPROV",
  businessUnit: "International"
}, {
  id: "DHIGH",
  firstName: "DEAN",
  lastName: "HIGHFIELD",
  email: "dean.highfield@essencemediacom.com",
  officeName: "MEDIACOM NORTH",
  securityGroup: "PRAPRGBY",
  businessUnit: "North"
}, {
  id: "DSTAND",
  firstName: "DAVID",
  lastName: "STANDALOFT",
  email: "david.standaloft@essencemediacom.com",
  officeName: "MEDIACOM NORTH",
  securityGroup: "PRAPROV",
  businessUnit: "North"
}, {
  id: "EBRAD",
  firstName: "EMMA",
  lastName: "BRADY",
  email: "emma.brady@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRBUY",
  businessUnit: "B12"
}, {
  id: "ELDAV",
  firstName: "ELLA",
  lastName: "DAVIES",
  email: "ella.davies@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRPO",
  businessUnit: "International"
}, {
  id: "ELIMA",
  firstName: "ERZA",
  lastName: "LIMANI",
  email: "erza.limani@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRPO",
  businessUnit: "International"
}, {
  id: "ELLES",
  firstName: "ELLIE",
  lastName: "ESPLEN",
  email: "ellie.esplen@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRPO",
  businessUnit: "International"
}, {
  id: "ESTRU",
  firstName: "EMMA",
  lastName: "STRUGGLES",
  email: "emma.struggles@essencemediacom.com",
  officeName: "MEDIACOM NORTH",
  securityGroup: "PRAPRGBY",
  businessUnit: "North"
}, {
  id: "GBARL",
  firstName: "GEORGINA",
  lastName: "BARLOW",
  email: "georgina.barlow@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRPO",
  businessUnit: "Dell"
}, {
  id: "GGILB",
  firstName: "GEORGE",
  lastName: "GILBERT",
  email: "george.gilbert@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRBUY",
  businessUnit: "Global"
}, {
  id: "GSPIN",
  firstName: "GEMMA",
  lastName: "SPINK",
  email: "gemma.spink@essencemediacom.com",
  officeName: "MEDIACOM NORTH",
  securityGroup: "PRAPRGBY",
  businessUnit: "North"
}, {
  id: "HANMC",
  firstName: "HANNAH",
  lastName: "MCLOUGHLIN",
  email: "hannah.mcloughlin@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRBUY",
  businessUnit: "International"
}, {
  id: "HAOUG",
  firstName: "HARJIT",
  lastName: "OUGHERA",
  email: "harjit.oughera@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRBUY",
  businessUnit: "B12"
}, {
  id: "HAWAL",
  firstName: "HARRIET",
  lastName: "WALDRON",
  email: "harriet.waldron@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRBUY",
  businessUnit: "B12"
}, {
  id: "HCONS",
  firstName: "HARLEY",
  lastName: "CONSTABLE",
  email: "harley.constable@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPROV",
  businessUnit: "International"
}, {
  id: "HLETR",
  firstName: "HIEU",
  lastName: "LETRUNG",
  email: "hieu.letrung1@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPROV",
  businessUnit: "International"
}, {
  id: "HMCCA",
  firstName: "HAYLEY",
  lastName: "MCCAULEY",
  email: "hayley.mccauley@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPROV",
  businessUnit: "Global"
}, {
  id: "HSPRI",
  firstName: "HENRY",
  lastName: "SPRINGATE",
  email: "henry.springate@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRBUY",
  businessUnit: "BU12"
}, {
  id: "HWHIT",
  firstName: "HELEN",
  lastName: "WHITLEY",
  email: "helen.whitley@essencemediacom.com",
  officeName: "MEDIACOM NORTH",
  securityGroup: "PRAPRGBY",
  businessUnit: "North"
}, {
  id: "HWILS",
  firstName: "HOLLY",
  lastName: "PARKER",
  email: "holly.parker@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRBUY",
  businessUnit: "International"
}, {
  id: "IMACD",
  firstName: "ISOBEL",
  lastName: "MACDOUGALL",
  email: "isobel.macdougall@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPROV",
  businessUnit: "eCom"
}, {
  id: "ISLAW",
  firstName: "ISLA",
  lastName: "WATSON",
  email: "isla.watson@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRPO",
  businessUnit: "BU12",
  specialty: "PPC"
}, {
  id: "JACKH",
  firstName: "JACK",
  lastName: "HARMON",
  email: "jack.harmon@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPBMQS",
  businessUnit: "International"
}, {
  id: "JACOL",
  firstName: "JAMIE",
  lastName: "COLLINS",
  email: "jamie.collins@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRBUY",
  businessUnit: "Scotland"
}, {
  id: "JANEW",
  firstName: "JANE",
  lastName: "WILSON",
  email: "jane.wilson@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRPO",
  businessUnit: "Scotland"
}, {
  id: "JASLA",
  firstName: "JADE",
  lastName: "SLATER",
  email: "jade.slater@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRPO",
  businessUnit: "Global"
}, {
  id: "JBOCK",
  firstName: "JEREMY",
  lastName: "BOCK",
  email: "jeremy.bock@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRBUY",
  businessUnit: "SEO",
  specialty: "SEO"
}, {
  id: "JCOLL",
  firstName: "JARED",
  lastName: "COLLINS",
  email: "jared.collins@essencemediacom.com",
  officeName: "MEDIACOM NORTH",
  securityGroup: "PRAPRPO",
  businessUnit: "North"
}, {
  id: "JGORN",
  firstName: "JOSHUA",
  lastName: "GORNELL",
  email: "joshua.gornell@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPBMQS",
  businessUnit: "BG3"
}, {
  id: "JHELM",
  firstName: "JOHN",
  lastName: "HELM",
  email: "john.helm@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPBMQS",
  businessUnit: "International"
}, {
  id: "JOCAP",
  firstName: "JOE",
  lastName: "CAPILDEO",
  email: "joe.capildeo@groupm.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPBMQS",
  businessUnit: "All"
}, {
  id: "JOLAR",
  firstName: "JOEL",
  lastName: "LARGE",
  email: "joel.large@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRBUY",
  businessUnit: "International"
}, {
  id: "JONWA",
  firstName: "JONATHAN",
  lastName: "WALLER",
  email: "jonathan.waller@essencemediacom.com",
  officeName: "MEDIACOM NORTH",
  securityGroup: "PRAPRGBY",
  businessUnit: "North"
}, {
  id: "JORSE",
  firstName: "JORDAN",
  lastName: "SEDDON",
  email: "jordan.seddon@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRBUY",
  businessUnit: "International"
}, {
  id: "KAREI",
  firstName: "KAREN",
  lastName: "REID",
  email: "karen.reid@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRBUY",
  businessUnit: "Print",
  specialty: "Print"
}, {
  id: "KATKN",
  firstName: "KATARINA",
  lastName: "KNAZEOVA",
  email: "katarina.knazeova@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRBUY",
  businessUnit: "International"
}, {
  id: "KATRE",
  firstName: "KATHRYN",
  lastName: "REID",
  email: "kathryn.reid@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRBUY",
  businessUnit: "BU3"
}, {
  id: "KBEAR",
  firstName: "KAYLEIGH",
  lastName: "BEARD",
  email: "kayleigh.beard@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRPO",
  businessUnit: "BU12",
  specialty: "Social"
}, {
  id: "KEMCG",
  firstName: "KELLY",
  lastName: "MCGUINNESS",
  email: "kelly.mcguinness@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPROV",
  businessUnit: "Global"
}, {
  id: "KGRAC",
  firstName: "KLAUDIA",
  lastName: "GRACZYK",
  email: "klaudia.graczyk@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRBUY",
  businessUnit: "PST"
}, {
  id: "KHAVE",
  firstName: "KRISHNA",
  lastName: "HAVELIWALA",
  email: "krishna.haveliwala@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRBUY",
  businessUnit: "Global"
}, {
  id: "KLEWIS",
  firstName: "KATIE",
  lastName: "LEWIS",
  email: "katie.lewis@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRBUY",
  businessUnit: "All"
}, {
  id: "KMILL",
  firstName: "KAYLEIGH",
  lastName: "MILLS",
  email: "kayleigh.mills@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRBUY",
  businessUnit: "Scotland"
}, {
  id: "KOGIL",
  firstName: "KIRSTY",
  lastName: "OGILVIE",
  email: "kirsty.ogilvie@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPBMQS",
  businessUnit: "BU5"
}, {
  id: "KSTEW",
  firstName: "KIRSTY",
  lastName: "ANDERSON",
  email: "kirsty.anderson@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRPO",
  businessUnit: "Scotland"
}, {
  id: "LAGOR",
  firstName: "LAUREN",
  lastName: "GORE",
  email: "lauren.gore@groupm.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPBMQS",
  businessUnit: "OpenDoor"
}, {
  id: "LASCOT",
  firstName: "LAURA",
  lastName: "SMITH",
  email: "laura.smith@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRPO",
  businessUnit: "BU12"
}, {
  id: "LFILB",
  firstName: "LAURENCE",
  lastName: "FILBY",
  email: "laurence.filby@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRPO",
  businessUnit: "BU5"
}, {
  id: "LIBRE",
  firstName: "LIAM",
  lastName: "BRENNAN",
  email: "liam.brennan1@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRBUY",
  businessUnit: "International"
}, {
  id: "LKUCU",
  firstName: "LADEN",
  lastName: "KUCUK",
  email: "laden.kucuk1@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRPO",
  businessUnit: "Global"
}, {
  id: "LKURT",
  firstName: "LEDI",
  lastName: "KURTULA",
  email: "ledi.kurtula@essencemediacom.com",
  officeName: "MEDIACOM NORTH",
  securityGroup: "PRAPROV",
  businessUnit: "North"
}, {
  id: "LTURN",
  firstName: "LUKE",
  lastName: "TURNER",
  email: "luke.turner@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPBYJM",
  businessUnit: "BG3"
}, {
  id: "LUPIC",
  firstName: "LUCY",
  lastName: "PICKERING",
  email: "lucy.pickering@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRBUY",
  businessUnit: "B12"
}, {
  id: "MACANT",
  firstName: "MAUD",
  lastName: "CANT",
  email: "maud.cant@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRGBY",
  businessUnit: "Scotland"
}, {
  id: "MAHOW",
  firstName: "MARGO",
  lastName: "HOWIE",
  email: "margo.howie@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRBUY",
  businessUnit: "eCom"
}, {
  id: "MAMAT",
  firstName: "MADELEINE",
  lastName: "MATHER",
  email: "madeleine.mather@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRBUY",
  businessUnit: "International"
}, {
  id: "MASSI",
  firstName: "MASSIMO",
  lastName: "MICHINI",
  email: "massimo.michini@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRPO",
  businessUnit: "International"
}, {
  id: "MBUFT",
  firstName: "MEGAN",
  lastName: "BUFTON",
  email: "megan.bufton@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRPO",
  businessUnit: "International"
}, {
  id: "MEWIL",
  firstName: "MESHA",
  lastName: "LUNT",
  email: "mesha.lunt@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRBUY",
  businessUnit: "BU12"
}, {
  id: "MICHT",
  firstName: "MICHAEL",
  lastName: "THOMSON",
  email: "michael.thomson@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPROV",
  businessUnit: "Scotland"
}, {
  id: "MJELMAN",
  firstName: "MARIAMA",
  lastName: "JELMAN",
  email: "mariama.jelman@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRPO",
  businessUnit: "International"
}, {
  id: "MKALU",
  firstName: "MWEWA",
  lastName: "KALUBA",
  email: "mwewa.kaluba@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRBUY",
  businessUnit: "Digital Practice",
  specialty: "Digital Practice"
}, {
  id: "MKOLL",
  firstName: "MARION",
  lastName: "KOLLEN",
  email: "marion.kollen@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPROV",
  businessUnit: "International"
}, {
  id: "MMIND",
  firstName: "MALINA",
  lastName: "MINDRU",
  email: "malina.mindru@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPROV",
  businessUnit: "Dell"
}, {
  id: "MNIKO",
  firstName: "MARIANA",
  lastName: "NIKOLAKAKI",
  email: "mariana.nikolakaki@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRPO",
  businessUnit: "BG3"
}, {
  id: "MSTIR3",
  firstName: "MATTHEW",
  lastName: "STIRLAND",
  email: "matthew.stirland@essencemediacom.com",
  officeName: "MEDIACOM NORTH",
  securityGroup: "PRAPRGBY",
  businessUnit: "North"
}, {
  id: "NCART",
  firstName: "NICK",
  lastName: "CARTER",
  email: "nick.carter@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPBMQS",
  businessUnit: "BG3"
}, {
  id: "NELIO",
  firstName: "NIAMH",
  lastName: "ELIOT",
  email: "niamh.eliot@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRBUY",
  businessUnit: "Global"
}, {
  id: "OJOSH",
  firstName: "OMKAR",
  lastName: "JOSHI",
  email: "omkar.joshi@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRBUY",
  businessUnit: "International"
}, {
  id: "OMCAL",
  firstName: "OLIVER",
  lastName: "MCALARY",
  email: "oliver.mcalary@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRPO",
  businessUnit: "Careers",
  specialty: "Careers"
}, {
  id: "PJAMESON",
  firstName: "PHIL",
  lastName: "JAMESON",
  email: "phil.jameson@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPROV",
  businessUnit: "BU5"
}, {
  id: "PSHRI",
  firstName: "PARESH",
  lastName: "SHRIGONDEKAR",
  email: "paresh.shrigondekar@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRBUY",
  businessUnit: "International"
}, {
  id: "RBARD",
  firstName: "REBECCA",
  lastName: "BARDEN",
  email: "rebecca.barden@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRBUY",
  businessUnit: "PST"
}, {
  id: "RCHAM",
  firstName: "RICHARD",
  lastName: "CHAMBERS",
  email: "richard.chambers@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRBUY",
  businessUnit: "B12"
}, {
  id: "RDIXO",
  firstName: "RACHEL",
  lastName: "DIXON",
  email: "rachel.dixon@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPROV",
  businessUnit: "Dell"
}, {
  id: "REONE",
  firstName: "REBECCA",
  lastName: "JONES",
  email: "rebecca.jones@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPROV",
  businessUnit: "International"
}, {
  id: "RESCO",
  firstName: "REECE",
  lastName: "SCOTT",
  email: "reece.scott@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRBUY",
  businessUnit: "Global"
}, {
  id: "RHETE",
  firstName: "RHEANNA",
  lastName: "TEJURA",
  email: "rheanna.tejura@groupm.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRBUY",
  businessUnit: "OpenMind"
}, {
  id: "RLITT",
  firstName: "RACHEL",
  lastName: "LITTLE",
  email: "rachel.little@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRBUY",
  businessUnit: "Scotland"
}, {
  id: "RMCDO",
  firstName: "REBECCA",
  lastName: "MCDONALD",
  email: "rebecca.mcdonald@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPROV",
  businessUnit: "North"
}, {
  id: "ROCOL",
  firstName: "ROB",
  lastName: "COLES",
  email: "rob.coles@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRBUY",
  businessUnit: "Global"
}, {
  id: "ROWAL",
  firstName: "ROBERT",
  lastName: "WALKER",
  email: "robert.walker@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPBMQS",
  businessUnit: "BG3"
}, {
  id: "RPALM",
  firstName: "REBECCA",
  lastName: "PALMER",
  email: "rebecca.palmer@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRBUY",
  businessUnit: "B12"
}, {
  id: "SBURT",
  firstName: "SARA",
  lastName: "BURTON",
  email: "sara.burton@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPROV",
  businessUnit: "International"
}, {
  id: "SCORE",
  firstName: "SILVIA",
  lastName: "CORREIA",
  email: "silvia.correia@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRBUY",
  businessUnit: "B12"
}, {
  id: "SCROW",
  firstName: "SAMMY",
  lastName: "CROW",
  email: "sammy.crow@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRPO",
  businessUnit: "Global"
}, {
  id: "SCUSH",
  firstName: "STEVE",
  lastName: "CUSHNAN",
  email: "steve.cushnan@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRBUY",
  businessUnit: "PST",
  specialty: "PST"
}, {
  id: "SHASL2",
  firstName: "SAM",
  lastName: "HASLAM",
  email: "sam.haslam@essencemediacom.com",
  officeName: "MEDIACOM NORTH",
  securityGroup: "PRAPRGBY",
  businessUnit: "North"
}, {
  id: "SHIKP",
  firstName: "SHIKHA",
  lastName: "PATEL",
  email: "shikha.patel@groupm.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRBUY",
  businessUnit: "OpenMind"
}, {
  id: "SHSHA",
  firstName: "SHAHYAD",
  lastName: "SHAHIR",
  email: "shahyad.shahir@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPROV",
  businessUnit: "BU12"
}, {
  id: "SLADA",
  firstName: "STEVE",
  lastName: "LADAN",
  email: "steve.ladan@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRBUY",
  businessUnit: "eCom"
}, {
  id: "SMEYER",
  firstName: "SARAH",
  lastName: "HEWITT",
  email: "sarah.hewitt@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRBUY",
  businessUnit: "BG3",
  specialty: "B12"
}, {
  id: "SSWEE",
  firstName: "SOPHIE",
  lastName: "SWEETLAND",
  email: "sophie.sweetland@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRPO",
  businessUnit: "BU12"
}, {
  id: "SZANO",
  firstName: "SIMONE",
  lastName: "ZANOLLA",
  email: "simone.zanolla@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRBUY",
  businessUnit: "International"
}, {
  id: "TEBUC",
  firstName: "TERRY",
  lastName: "BUCKINGHAM",
  email: "terry.buckingham@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPBMQS",
  businessUnit: "BG3"
}, {
  id: "THODE",
  firstName: "THOMAS",
  lastName: "DENMAN",
  email: "thomas.denman@groupm.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRBUY",
  businessUnit: "OpenDoor"
}, {
  id: "TLATH",
  firstName: "TOM",
  lastName: "LATHAM",
  email: "tom.latham@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPBMQS",
  businessUnit: "BU3"
}, {
  id: "TLOON",
  firstName: "TASH",
  lastName: "LOONEY",
  email: "tash.looney@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRBUY",
  businessUnit: "CCP",
  specialty: "CCP"
}, {
  id: "TMYLE",
  firstName: "TOBY",
  lastName: "MYLES",
  email: "toby.myles@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRBUY",
  businessUnit: "International"
}, {
  id: "TUDAL",
  firstName: "TATJANA",
  lastName: "UDALOVA",
  email: "tatjana.udalova@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPBMQS",
  businessUnit: "All"
}, {
  id: "VALDA",
  firstName: "VALENTINA",
  lastName: "DAMIANI",
  email: "valentina.damiani@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPROV",
  businessUnit: "OpenMind"
}, {
  id: "VIJMU",
  firstName: "VIJAY",
  lastName: "MUTHUKRISHNAN",
  email: "vijay.muthukrishnan@groupm.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRBUY",
  businessUnit: "OpenDoor"
}, {
  id: "VIOAN",
  firstName: "VASILIKI",
  lastName: "IOANNIDOU",
  email: "vasiliki.ioannidou@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPROV",
  businessUnit: "Dell"
}, {
  id: "VLOUD",
  firstName: "VERONIKA",
  lastName: "LOUDOVA",
  email: "veronika.loudova@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRBUY",
  businessUnit: "International"
}, {
  id: "WBLAN",
  firstName: "WILL",
  lastName: "BLANK",
  email: "will.blank@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRBUY",
  businessUnit: "International"
}, {
  id: "YNDLO",
  firstName: "YOLANDA",
  lastName: "NDLOVU",
  email: "yolanda.ndlovu@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPRPO",
  businessUnit: "BU5"
}, {
  id: "YPAPA",
  firstName: "YIOTA",
  lastName: "PAPATHOMA",
  email: "yiota.papathoma@essencemediacom.com",
  officeName: "MEDIACOM",
  securityGroup: "PRAPROV",
  businessUnit: "Dell"
}].map(approver => ({
  ...approver,
  // Add the new companyUserIds field, defaulting to an empty array
  companyUserIds: companyUserIdsMap[approver.id] || []
}));

export const businessUnits = [...new Set(approversData.map(a => a.businessUnit))].filter(Boolean);
export const clients = [...new Set(approversData.map(a => a.officeName))].filter(Boolean);

// Collect and export all unique Company User IDs
const allCompanyUserIds = new Set();
approversData.forEach(approver => {
  if (approver.companyUserIds) {
    approver.companyUserIds.forEach(id => allCompanyUserIds.add(id));
  }
});
export const companyUserIdsList = [...allCompanyUserIds].sort();
