/**
 * @fileoverview Defines the data source for the approvers page.
 * Contains a list of approvers with their details and exported arrays for filtering options.
 */

/**
 * Array of approver objects containing their details.
 * @type {Array<Approver>}
 * @property {string} id - The unique identifier for the approver.
 * @property {string} firstName - The first name of the approver.
 * @property {string} lastName - The last name of the approver.
 * @property {string} email - The email address of the approver.
 * @property {string} officeName - The office/client name associated with the approver.
 * @property {string} securityGroup - The security group code for the approver.
 * @property {string} businessUnit - The business unit the approver belongs to.
 * @property {string} [specialty] - The specialty area of the approver (optional).
 */
export const approversData = [
  { id: "ADCRO", firstName: "Adam", lastName: "Crow", email: "adam.crow@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPROV", businessUnit: "All" },
  { id: "ADENE", firstName: "Adeel", lastName: "Nehim", email: "adeel.nehim@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "Social", specialty: "Social" },
  { id: "ADMCC", firstName: "Adeola", lastName: "Mccabe", email: "adeola.mccabe@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "Social", specialty: "Social" },
  { id: "ADSMI", firstName: "Adam", lastName: "Smith", email: "adam.smith1@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "PPC", specialty: "PPC" },
  { id: "AMGIBS", firstName: "Amelia", lastName: "Monks", email: "amelia.monks@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "AMILE", firstName: "Ana", lastName: "Cuellar", email: "ana.cuellar@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "SEO", specialty: "SEO" },
  { id: "AMUEL", firstName: "Adrian", lastName: "Mueller", email: "adrian.mueller@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPROV", businessUnit: "All" },
  { id: "ANCOO", firstName: "Andrew", lastName: "Cook", email: "andrew.cook@essencemediacom.com", officeName: "MEDIACOM NORTH", securityGroup: "PRAPRGBY", businessUnit: "All" },
  { id: "ANGIM", firstName: "Anna", lastName: "Gim", email: "anna.gim@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "ANIKO", firstName: "Athina", lastName: "Nikol", email: "athina.nikol@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "APYKE", firstName: "Adam", lastName: "Pyke", email: "adam.pyke@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "AROBE", firstName: "Amy", lastName: "Roberts", email: "amy.roberts@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "BG3" },
  { id: "ASHEI", firstName: "Ashleigh", lastName: "Heitman", email: "ashleigh.heitman@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPROV", businessUnit: "All" },
  { id: "ASTEP", firstName: "Adam", lastName: "Stephens", email: "adam.stephens@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPROV", businessUnit: "All" },
  { id: "AWIJE", firstName: "Adrian", lastName: "Wijenathan", email: "adrian.wijenathan@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "BDRUR", firstName: "Beth", lastName: "Drury", email: "beth.drury@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "BESTA", firstName: "Ben", lastName: "Stanhope", email: "ben.stanhope1@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRPO", businessUnit: "All" },
  { id: "BEWIL", firstName: "Becci", lastName: "Wilson", email: "becci.wilson@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "BISAM", firstName: "Billy", lastName: "Samuels", email: "billy.samuels@essencemediacom.com", officeName: "MEDIACOM NORTH", securityGroup: "PRAPRGBY", businessUnit: "All" },
  { id: "BMALA", firstName: "Ben", lastName: "Malam", email: "ben.malam@essencemediacom.com", officeName: "MEDIACOM NORTH", securityGroup: "PRAPRGBY", businessUnit: "All" },
  { id: "BSHEA", firstName: "Briony", lastName: "Sheard", email: "briony.sheard@essencemediacom.com", officeName: "MEDIACOM NORTH", securityGroup: "PRAPROV", businessUnit: "All" },
  { id: "CBECK", firstName: "Christofer", lastName: "Beckman", email: "christofer.beckman@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "CMAST", firstName: "Caroline", lastName: "Mastromauro", email: "caroline.mastromauro@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "CMCWH", firstName: "Caroline", lastName: "Mcwhirter", email: "caroline.mcwhirter@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPROV", businessUnit: "All" },
  { id: "CRIDS", firstName: "Carys", lastName: "Profitdale", email: "carys.profitdale@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "CROSE", firstName: "Cheyenne", lastName: "Rose", email: "cheyenne.rose@essencemediacom.com", officeName: "ESSENCE", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "CSAUN", firstName: "Charlie", lastName: "Saunders", email: "charlie.saunders@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "CTURN", firstName: "Chris", lastName: "Turner", email: "chris.turner@essencemediacom.com", officeName: "MEDIACOM NORTH", securityGroup: "PRAPROV", businessUnit: "All" },
  { id: "CTUTT", firstName: "Connor", lastName: "Tuttle", email: "connor.tuttle@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "DADAR", firstName: "Danielle", lastName: "Darko", email: "danielle.darko@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPBMQS", businessUnit: "All" },
  { id: "DANBE", firstName: "Danielle", lastName: "Bennett", email: "danielle.bennett@essencemediacom.com", officeName: "MEDIACOM NORTH", securityGroup: "PRAPRGBY", businessUnit: "All" },
  { id: "DAROBI", firstName: "Dan", lastName: "Robinson", email: "dan.robinson@essencemediacom.com", officeName: "MEDIACOM NORTH", securityGroup: "PRAPRGBY", businessUnit: "All" },
  { id: "DCABU", firstName: "Damla", lastName: "Cabuk", email: "damla.cabuk@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "DDWIN", firstName: "Danique", lastName: "De Winter", email: "danique.dewinter@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPROV", businessUnit: "All" },
  { id: "DHIGH", firstName: "Dean", lastName: "Highfield", email: "dean.highfield@essencemediacom.com", officeName: "MEDIACOM NORTH", securityGroup: "PRAPRGBY", businessUnit: "All" },
  { id: "DSTAND", firstName: "David", lastName: "Standaloft", email: "david.standaloft@essencemediacom.com", officeName: "MEDIACOM NORTH", securityGroup: "PRAPROV", businessUnit: "All" },
  { id: "EBRAD", firstName: "Emma", lastName: "Brady", email: "emma.brady@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "ELDAV", firstName: "Ella", lastName: "Davies", email: "ella.davies@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRPO", businessUnit: "All" },
  { id: "ELIMA", firstName: "Erza", lastName: "Limani", email: "erza.limani@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRPO", businessUnit: "All" },
  { id: "ELLES", firstName: "Ellie", lastName: "Esplen", email: "ellie.esplen@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRPO", businessUnit: "All" },
  { id: "EMCCA", firstName: "Emma", lastName: "Mccarthy", email: "emma.mccarthy@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "FMCKI", firstName: "Faye", lastName: "Mckinney", email: "faye.mckinney@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "FPIAN", firstName: "Francesco", lastName: "Piani", email: "francesco.piani@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "GFARR", firstName: "Grace", lastName: "Farrer", email: "grace.farrer@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "GLEAF", firstName: "Grace", lastName: "Leaford", email: "grace.leaford@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "GMCLA", firstName: "Georgina", lastName: "Mclauchlan", email: "georgina.mclauchlan@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "GNELS", firstName: "George", lastName: "Nelson", email: "george.nelson@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "HAVAN", firstName: "Harvey", lastName: "Vann", email: "harvey.vann@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRPO", businessUnit: "All" },
  { id: "HCLAR", firstName: "Hannah", lastName: "Clarke", email: "hannah.clarke@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "HKATH", firstName: "Hannah", lastName: "Kathri", email: "hannah.kathri@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "HNEAL", firstName: "Hollie", lastName: "Neal", email: "hollie.neal@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "HWILL", firstName: "Hamza", lastName: "Williams", email: "hamza.williams@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "HYADL", firstName: "Haya", lastName: "Dl", email: "haya.dl@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "JACOL", firstName: "Jack", lastName: "Collins", email: "jack.collins@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "JALVE", firstName: "Jake", lastName: "Alves", email: "jake.alves@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "JAMGI", firstName: "Jamie", lastName: "Gibson", email: "jamie.gibson@essencemediacom.com", officeName: "MEDIACOM NORTH", securityGroup: "PRAPRGBY", businessUnit: "All" },
  { id: "JBENS", firstName: "Jake", lastName: "Benson", email: "jake.benson@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "JBONN", firstName: "Julia", lastName: "Bonny", email: "julia.bonny@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "JBROO", firstName: "James", lastName: "Brooks", email: "james.brooks@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "BG2", specialty: "BG2" },
  { id: "JCHAP", firstName: "Joe", lastName: "Chapman", email: "joe.chapman@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "JCLAD", firstName: "Jayde", lastName: "Cladd", email: "jayde.cladd@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "JDEAN", firstName: "Jack", lastName: "Dean", email: "jack.dean@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "JELTO", firstName: "Jess", lastName: "Elton", email: "jess.elton@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "JENVA", firstName: "Jake", lastName: "Envall", email: "jake.envall@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "JFORD", firstName: "Jess", lastName: "Ford", email: "jess.ford@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "JGRAN", firstName: "Jack", lastName: "Grant", email: "jack.grant@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "JHARR", firstName: "Jack", lastName: "Harrison", email: "jack.harrison@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "JHILL", firstName: "James", lastName: "Hills", email: "james.hills@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "JKING", firstName: "Jade", lastName: "King", email: "jade.king@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "JLUNA", firstName: "Javier", lastName: "Luna", email: "javier.luna@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "JMICK", firstName: "James", lastName: "Mickiewicz", email: "james.mickiewicz@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "JMOTT", firstName: "James", lastName: "Mott", email: "james.mott@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "JOOHO", firstName: "Joo", lastName: "Ho", email: "joo.ho@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "JPARK", firstName: "Jay", lastName: "Park", email: "jay.park@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "JSHER", firstName: "Jack", lastName: "Sherman", email: "jack.sherman@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "JSMAL", firstName: "James", lastName: "Smalley", email: "james.smalley@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "JTURN", firstName: "James", lastName: "Turner", email: "james.turner@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "KATKI", firstName: "Katrina", lastName: "Atkin", email: "katrina.atkin@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "KBULL", firstName: "Kristy", lastName: "Bull", email: "kristy.bull@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "KCADE", firstName: "Kavitha", lastName: "Cadeaux", email: "kavitha.cadeaux@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "KDAVI", firstName: "Kate", lastName: "Davis", email: "kate.davis@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "KGRIM", firstName: "Kate", lastName: "Grimshaw", email: "kate.grimshaw@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "KHUNG", firstName: "Kevin", lastName: "Hung", email: "kevin.hung@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "KJAME", firstName: "Kirsty", lastName: "James", email: "kirsty.james@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "KKEMP", firstName: "Kathryn", lastName: "Kemp", email: "kathryn.kemp@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "KMACD", firstName: "Katie", lastName: "Macdonald", email: "katie.macdonald@essencemediacom.com", officeName: "MEDIACOM NORTH", securityGroup: "PRAPRGBY", businessUnit: "All" },
  { id: "KMART", firstName: "Kate", lastName: "Martin", email: "kate.martin@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "KMERR", firstName: "Katie", lastName: "Merrick", email: "katie.merrick@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "KPARS", firstName: "Kate", lastName: "Parsons", email: "kate.parsons@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "KPEAR", firstName: "Kathryn", lastName: "Pearson", email: "kathryn.pearson@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "KRICH", firstName: "Katie", lastName: "Richards", email: "katie.richards@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "KSTIL", firstName: "Kelly", lastName: "Stiles", email: "kelly.stiles@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "KTREB", firstName: "Kamil", lastName: "Trebnicki", email: "kamil.trebnicki@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "LAURP", firstName: "Lauren", lastName: "Purvis", email: "lauren.purvis@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "LBROW", firstName: "Laura", lastName: "Brown", email: "laura.brown@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "LCHEC", firstName: "Luca", lastName: "Checchetto", email: "luca.checchetto@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "LDICK", firstName: "Lucy", lastName: "Dickens", email: "lucy.dickens@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "LDOYL", firstName: "Lucy", lastName: "Doyle", email: "lucy.doyle@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "LGRAS", firstName: "Luke", lastName: "Grassi", email: "luke.grassi@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "LHUNT", firstName: "Lyndsey", lastName: "Hunt", email: "lyndsey.hunt@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "LJAME", firstName: "Louise", lastName: "James", email: "louise.james@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "LKYLE", firstName: "Luke", lastName: "Kyle", email: "luke.kyle@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "LLOUR", firstName: "Louisa", lastName: "Lourdes", email: "louisa.lourdes@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "LMART", firstName: "Lucy", lastName: "Martin", email: "lucy.martin@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "LMCKA", firstName: "Lucy", lastName: "Mckay", email: "lucy.mckay@essencemediacom.com", officeName: "MEDIACOM NORTH", securityGroup: "PRAPRGBY", businessUnit: "All" },
  { id: "LMORG", firstName: "Laura", lastName: "Morgan", email: "laura.morgan@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "LPAYN", firstName: "Lara", lastName: "Payne", email: "lara.payne@essencemediacom.com", officeName: "ESSENCE", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "LRIDE", firstName: "Lucy", lastName: "Rideal", email: "lucy.rideal@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "LROYS", firstName: "Lucy", lastName: "Royston", email: "lucy.royston@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "LSAUN", firstName: "Lucy", lastName: "Saunders", email: "lucy.saunders@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "LSCON", firstName: "Laura", lastName: "Scon", email: "laura.scon@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "LTOMP", firstName: "Lauren", lastName: "Tompkins", email: "lauren.tompkins@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "LWOLF", firstName: "Lewis", lastName: "Wolfe", email: "lewis.wolfe@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "MAPPL", firstName: "Max", lastName: "Appleby", email: "max.appleby@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "MARQU", firstName: "Maria", lastName: "Arquist", email: "maria.arquist@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "MBEAC", firstName: "Molly", lastName: "Beach", email: "molly.beach@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "MBHOW", firstName: "Mark", lastName: "Bhowmick", email: "mark.bhowmick@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "MCALD", firstName: "Michael", lastName: "Caldwell", email: "michael.caldwell@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "MCHUR", firstName: "Mia", lastName: "Churchill", email: "mia.churchill@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "MDAVI", firstName: "Megan", lastName: "Davis", email: "megan.davis@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "MGOUG", firstName: "Martin", lastName: "Gough", email: "martin.gough@essencemediacom.com", officeName: "MEDIACOM NORTH", securityGroup: "PRAPRGBY", businessUnit: "All" },
  { id: "MHAQU", firstName: "Milhan", lastName: "Haque", email: "milhan.haque@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "MJAVI", firstName: "Maria", lastName: "Javidi", email: "maria.javidi@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "MKANT", firstName: "Michelle", lastName: "Kanter", email: "michelle.kanter@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "MKOVA", firstName: "Martin", lastName: "Kovacs", email: "martin.kovacs@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "MKRAM", firstName: "Max", lastName: "Kramer", email: "max.kramer@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRPO", businessUnit: "All" },
  { id: "MMCDA", firstName: "Megan", lastName: "Mcdaid", email: "megan.mcdaid@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "MMOGA", firstName: "Molly", lastName: "Mogan", email: "molly.mogan@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "MMORG", firstName: "Millie", lastName: "Morgan", email: "millie.morgan@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "MOWKE", firstName: "Mohammed", lastName: "Owkeef", email: "mohammed.owkeef@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "MPAGE", firstName: "Megan", lastName: "Page", email: "megan.page@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "MPARL", firstName: "Megan", lastName: "Parlett", email: "megan.parlett@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "MPERS", firstName: "Matt", lastName: "Persse", email: "matt.persse@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "MREED", firstName: "Max", lastName: "Reed", email: "max.reed@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "MSADE", firstName: "Muktar", lastName: "Sadeghi", email: "muktar.sadeghi@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "MSHAH", firstName: "Megan", lastName: "Shah", email: "megan.shah@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "MTHOM", firstName: "Michael", lastName: "Thompson", email: "michael.thompson@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "MWATK", firstName: "Megan", lastName: "Watkins", email: "megan.watkins@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "NCASE", firstName: "Niall", lastName: "Casey", email: "niall.casey@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPROV", businessUnit: "All" },
  { id: "NCLIF", firstName: "Nikki", lastName: "Clifford", email: "nikki.clifford@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "BG1", specialty: "BG1" },
  { id: "NCOOP", firstName: "Nico", lastName: "Cooper", email: "nico.cooper@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "NFORD", firstName: "Nathan", lastName: "Ford", email: "nathan.ford@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "NJONE", firstName: "Niall", lastName: "Jones", email: "niall.jones@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "NKANE", firstName: "Niall", lastName: "Kane", email: "niall.kane@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "NKEEF", firstName: "Niamh", lastName: "Keeffe", email: "niamh.keeffe@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "NPARA", firstName: "Nikhil", lastName: "Parate", email: "nikhil.parate@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "NROBE", firstName: "Nick", lastName: "Roberts", email: "nick.roberts@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "NSHAR", firstName: "Nikita", lastName: "Sharma", email: "nikita.sharma@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "NSTEV", firstName: "Niall", lastName: "Stevens", email: "niall.stevens@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "OSAIN", firstName: "Oliver", lastName: "Sainsbury", email: "oliver.sainsbury@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "OWAIT", firstName: "Olivia", lastName: "Waite", email: "olivia.waite@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "PCAMP", firstName: "Paul", lastName: "Campbell", email: "paul.campbell@essencemediacom.com", officeName: "MEDIACOM NORTH", securityGroup: "PRAPRGBY", businessUnit: "All" },
  { id: "RAGAR", firstName: "Rachel", lastName: "Agarwal", email: "rachel.agarwal@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "RBENN", firstName: "Ruby", lastName: "Bennett", email: "ruby.bennett@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "RCONA", firstName: "Rob", lastName: "Conan", email: "rob.conan@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "RCOWA", firstName: "Ruth", lastName: "Cowan", email: "ruth.cowan@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "RFERR", firstName: "Ross", lastName: "Ferrari", email: "ross.ferrari@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "RGILL", firstName: "Robyn", lastName: "Gillham", email: "robyn.gillham@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "RHIND", firstName: "Rebecca", lastName: "Hind", email: "rebecca.hind@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "RHOLD", firstName: "Robyn", lastName: "Holder", email: "robyn.holder@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "RMOOR", firstName: "Rachel", lastName: "Moore", email: "rachel.moore@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "RMORR", firstName: "Rebecca", lastName: "Morris", email: "rebecca.morris@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "RSHAR", firstName: "Rahul", lastName: "Sharma", email: "rahul.sharma@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "RWAIN", firstName: "Rebecca", lastName: "Wainwright", email: "rebecca.wainwright@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "SADUL", firstName: "Sherin", lastName: "Aduloju", email: "sherin.aduloju@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "SALVA", firstName: "Sofia", lastName: "Alvarez", email: "sofia.alvarez@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "SARNO", firstName: "Sabrina", lastName: "Arnold", email: "sabrina.arnold@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "SBOON", firstName: "Shane", lastName: "Boone", email: "shane.boone@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "SCLAR", firstName: "Sophie", lastName: "Clarke", email: "sophie.clarke@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "SDAVI", firstName: "Sophie", lastName: "Davis", email: "sophie.davis@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "SENGU", firstName: "Sam", lastName: "English", email: "sam.english@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "SGREE", firstName: "Sophie", lastName: "Green", email: "sophie.green@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "SHANE", firstName: "Shaun", lastName: "Hanley", email: "shaun.hanley@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "SLIGH", firstName: "Sian", lastName: "Light", email: "sian.light@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "SMIRR", firstName: "Stephen", lastName: "Mirrlees", email: "stephen.mirrlees@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "SNELA", firstName: "Sara", lastName: "Nelson", email: "sara.nelson@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "SPETR", firstName: "Sofia", lastName: "Petrides", email: "sofia.petrides@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "SQUIC", firstName: "Sophie", lastName: "Quick", email: "sophie.quick@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "SRIDH", firstName: "Shanki", lastName: "Ridhwan", email: "shanki.ridhwan@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "SSHAW", firstName: "Sean", lastName: "Shaw", email: "sean.shaw@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "SWILS", firstName: "Sophie", lastName: "Wilson", email: "sophie.wilson@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "SYANG", firstName: "Sarah", lastName: "Yang", email: "sarah.yang@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "TBAUL", firstName: "Tom", lastName: "Baulderstone", email: "tom.baulderstone@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "TLLAW", firstName: "Tayla", lastName: "Llawry", email: "tayla.llawry@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "TMARR", firstName: "Toby", lastName: "Marr", email: "toby.marr@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "TOBEN", firstName: "Tanja", lastName: "Obendorf", email: "tanja.obendorf@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "TRING", firstName: "Tony", lastName: "Ring", email: "tony.ring@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "TROWE", firstName: "Tom", lastName: "Rowe", email: "tom.rowe@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "TSHEP", firstName: "Tammy", lastName: "Shepherd", email: "tammy.shepherd@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "VSING", firstName: "Vikrant", lastName: "Singh", email: "vikrant.singh@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "WWILL", firstName: "Will", lastName: "Williams", email: "will.williams@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "YHOPE", firstName: "Yusuf", lastName: "Hopen", email: "yusuf.hopen@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" },
  { id: "ZCHOI", firstName: "Zoe", lastName: "Choi", email: "zoe.choi@essencemediacom.com", officeName: "MEDIACOM", securityGroup: "PRAPRBUY", businessUnit: "All" }
];

/**
 * Array of unique business units extracted from the approvers data.
 * @type {Array<string>}
 */
export const businessUnits = [...new Set(approversData.map(a => a.businessUnit))].filter(Boolean);

/**
 * Array of unique client names (office names) extracted from the approvers data.
 * @type {Array<string>}
 */
export const clients = [...new Set(approversData.map(a => a.officeName))].filter(Boolean);
